package cmd

import (
	"log"
	"time"

	"github.com/idprm/go-football-alert/internal/domain/entity"
	"gorm.io/gorm"
)

func seederDB(db *gorm.DB) {
	var country []entity.Country
	var service []entity.Service
	var content []entity.Content
	var schedule []entity.Schedule
	var menu []entity.Menu
	//
	var countries = []entity.Country{
		{
			ID:       1,
			Name:     "MALI",
			Code:     "223",
			TimeZone: "GMT",
			Currency: "CFA",
		},
		{
			ID:       2,
			Name:     "GUINEE",
			Code:     "224",
			TimeZone: "GMT",
			Currency: "GNF",
		},
	}

	var services = []entity.Service{
		{
			ID:         1,
			CountryID:  1,
			Category:   "creditgoal",
			Name:       "Credit Goal Daily",
			Code:       "CG1",
			Package:    "daily",
			Price:      100,
			RewardGoal: 10,
			RenewalDay: 1,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         2,
			CountryID:  1,
			Category:   "prediction",
			Name:       "Prediction & Win Daily",
			Code:       "PW1",
			Package:    "daily",
			Price:      50,
			RewardGoal: 10,
			RenewalDay: 1,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         3,
			CountryID:  1,
			Category:   "follow-team",
			Name:       "Follow Team Daily",
			Code:       "FT1",
			Package:    "daily",
			Price:      200,
			RewardGoal: 0,
			RenewalDay: 1,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         4,
			CountryID:  1,
			Category:   "follow-competition",
			Name:       "Follow Competition Daily",
			Code:       "FC",
			Package:    "daily",
			Price:      200,
			RewardGoal: 0,
			RenewalDay: 1,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         5,
			CountryID:  1,
			Category:   "creditgoal",
			Name:       "Credit Goal Weekly",
			Code:       "CG7",
			Package:    "weekly",
			Price:      100,
			RewardGoal: 10,
			RenewalDay: 7,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         6,
			CountryID:  1,
			Category:   "prediction",
			Name:       "Prediction & Win Weekly",
			Code:       "PW7",
			Package:    "weekly",
			Price:      50,
			RewardGoal: 10,
			RenewalDay: 7,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         7,
			CountryID:  1,
			Category:   "follow-team",
			Name:       "Follow Team Weekly",
			Code:       "FT7",
			Package:    "weekly",
			Price:      200,
			RewardGoal: 0,
			RenewalDay: 7,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         8,
			CountryID:  1,
			Category:   "follow-competition",
			Name:       "Follow Competition Weekly",
			Code:       "FC",
			Package:    "weekly",
			Price:      200,
			RewardGoal: 0,
			RenewalDay: 7,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         9,
			CountryID:  1,
			Category:   "creditgoal",
			Name:       "Credit Goal Monthly",
			Code:       "CG30",
			Package:    "monthly",
			Price:      100,
			RewardGoal: 10,
			RenewalDay: 30,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         10,
			CountryID:  1,
			Category:   "prediction",
			Name:       "Prediction & Win Monthly",
			Code:       "PW30",
			Package:    "monthly",
			Price:      50,
			RewardGoal: 10,
			RenewalDay: 30,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         11,
			CountryID:  1,
			Category:   "follow-team",
			Name:       "Follow Team Monthly",
			Code:       "FT30",
			Package:    "monthly",
			Price:      200,
			RewardGoal: 0,
			RenewalDay: 30,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         12,
			CountryID:  1,
			Category:   "follow-competition",
			Name:       "Follow Competition Monthly",
			Code:       "FC30",
			Package:    "monthly",
			Price:      200,
			RewardGoal: 0,
			RenewalDay: 30,
			TrialDay:   0,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
	}

	var contents = []entity.Content{
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_CREDIT_GOAL_SUB,
			Value:    "Credit Goal: Votre participation a ete enregistree. Si {team} marque des buts lors du prochain match, vous recevrez {reward_per_goal}{currency} de credit par but. {price}{curency}/souscription",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_CREDIT_GOAL_ALREADY_SUB,
			Value:    "Credit Goal: Desole, vous avez deja une equipe favorite pour le prochain match de {league}. Vous pourrez choisir une autre equipe pour la journee suivante au {sc}.",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_CREDIT_GOAL_UNVALID_SUB,
			Value:    "Credit Goal: Desole, votre choix n est pas valide. Renvoyez par SMS au {sc} votre equipe favorite pour le prochain match. {price}{currency}/souscription",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_CREDIT_GOAL_MATCH_END_PAYOUT,
			Value:    "Credit Goal: Felicitations! Le score final du match {home} - {away} est {score}. Votre compte va etre credite de {price}{currency} [CFA]",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_CREDIT_GOAL_MATCH_INCENTIVE,
			Value:    "Credit Goal: la prochaine journee de {league} va commencer. Soutenez votre equipe et gagnez du credit. Envoyez au {sc} votre equipe. {price}{currency}/souscription",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_SUB,
			Value:    "Prono: Faites vos pronostics pour {home} - {away}. Envoyez au {sc}: {league}[12] plus [1] pour {home}, [2] pour {away} ou [3] pour un nul. {price}{currency}/SMS",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_SUB_BET_WIN,
			Value:    "Prono: Votre pronostic a ete enregistre avec une victoire de: {winner}. Votre compte a ete debite de {price}{currency} [CFA]. Bonne Chance!",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_SUB_BET_DRAW,
			Value:    "Prono: Votre pronostic est un match nul pour le match {home} - {away}. Votre compte a ete debite de {price}{currency} [CFA]. Bonne Chance!",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_UNVALID_SUB,
			Value:    "Prono: Desole, votre choix n est pas valide. Renvoyez votre choix au {sc} ou le nom de votre competition. {price}{currency}/SMS",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_SUB_REJECT_MATCH_END,
			Value:    "Prono: Desole, cette competition est terminee. Envoyez le nom de votre competition au {sc} pour recevoir les invitations a pronostiquer. {price}{currency}/SMS",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_SUB_REJECT_MATCH_STARTED,
			Value:    "Prono: Desole, vous ne pouvez plus faire de pronostics sur ce match. SMS Confirmation Retentez votre chance Free of charge SMS Text Template: G21(NEW) pour le prochain match {price}{currency}/SMS",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_MATCH_END_WINNER_AIRTIME,
			Value:    "Prono: Bravo! Bon pronostic pour le match {home} - {away}, vous avez gagne {reward}{currency} de credit de com par tirage au sort. Votre compte sera credite sous 48h.",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_MATCH_END_WINNER_LOTERY,
			Value:    "Bravo! Vous avez fait un bon pronostic pour le match {home} - {away}, vous venez de gagner un lot, aller à la boutique Orange pour les obtenir.",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_MATCH_END_LUCKY_LOSER,
			Value:    "Prono: Vous avez fait un bon pronostic, mais vous n avez pas ete tire au sort pour gagner {reward}{currency}. Retentez votre chance pour le prochain match au {sc}. {price}{currency}/SMS",
		},
		{
			Category: ACT_NOTIFICATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_MATCH_END_LOSER_NOTIF,
			Value:    "Prono: Desole! Votre pronostic n a pas ete le bon pour le match {home}-{away}. Retentez votre chance pour les prochains matchs .Bonne chance!",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_TEAM_SUB,
			Value:    "SMS Alerte: Vous avez souscrit avec succes pour suivre votre equipe favorite! Jusqu au {date}/{month} vous recevrez toutes les infos en direct. {price}{currency}/souscription",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_TEAM_UNVALID_SUB,
			Value:    "SMS Alerte: Desole, votre choix n est pas valide. Envoyez de nouveau au {sc} le nom de votre equipe pour obtenir toutes les infos. {price}{currency}/souscription",
		},
		{
			Category: ACT_NOTIFICATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_TEAM_EXPIRE_SUB,
			Value:    "SMS Alerte: Desole mais votre abonnement pour suivre votre equipe vient de se terminer. Pour le renouveler, envoyer au {sc} le nom de l equipe a suivre. {price}{currency}",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_COMPETITION_SUB,
			Value:    "SMS Alerte: Vous avez souscrit avec succes pour suivre {league}! Jusqu au {day}/{month} vous recevrez toutes les infos en direct. {price}{currency}/souscription",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_COMPETITION_UNVALID_SUB,
			Value:    "SMS Alerte: Desole, mais votre choix n est pas valide. Renvoyez au {sc} la competition que vous voulez suivre en direct. {price}{currency}/SMS",
		},
		{
			Category: ACT_NOTIFICATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_COMPETITION_EXPIRE_SUB,
			Value:    "SMS Alerte: Desole mais votre abonnement pour suivre votre competition vient de se terminer. Pour le renouveler, envoyer au {sc} le nom de l equipe a suivre. {price}{currency}/SMS",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_CONFIRMATION,
			Value:    "Info Services FFC: [#157#] USSD /[981] SMS Alerte Equipe /[9009] - SMS Alerte Competition /[###] SMS Alerte a la demande /[944] Credit Goal /[985] Pronostic",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_INFO,
			Value:    "Info Services FFC: [#157#] USSD /[981] SMS Alerte Equipe /[9009] - SMS Alerte Competition /[###] SMS Alerte a la demande /[944] Credit Goal /[985] Pronostic",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_STOP,
			Value:    "Services FFC: Vous venez d envoyer STOP. Orange vous remercie d avoir utiliser nos services! Visitez www.orange.cm pour en savoir plus sur Football Fan Club",
		},
	}

	var schedules = []entity.Schedule{
		{
			CountryID:  1,
			Name:       ACT_RENEWAL,
			PublishAt:  time.Now(),
			UnlockedAt: time.Now(),
			IsUnlocked: false,
		},
		{
			CountryID:  1,
			Name:       ACT_PREDICTION,
			PublishAt:  time.Now(),
			UnlockedAt: time.Now(),
			IsUnlocked: false,
		},
		{
			CountryID:  1,
			Name:       ACT_CREDIT_GOAL,
			PublishAt:  time.Now(),
			UnlockedAt: time.Now(),
			IsUnlocked: false,
		},
		{
			CountryID:  1,
			Name:       ACT_FOLLOW_COMPETITION,
			PublishAt:  time.Now(),
			UnlockedAt: time.Now(),
			IsUnlocked: false,
		},
		{
			CountryID:  1,
			Name:       ACT_FOLLOW_TEAM,
			PublishAt:  time.Now(),
			UnlockedAt: time.Now(),
			IsUnlocked: false,
		},
	}

	/**
	1.  #101#36#1 : Live match (Confirm Message)
	2.  #101#36#2 : Flash News (Confirm Message)
	3.  #101#36#3 : Crédit Goal (Confirm Message)
	4.  #101#36#4 : Champ. Mali (Confirm Message)
	5.  #101#36#5 : Prédiction (Confirm Message)
	6.  #101#36#6 : SMS Alerte (Confirm Message)
	7.  #101#36#7 : Kit Foot (Confirm Message)
	8.  #101#36#8 : Foot Europe (Free Access)
	9.  #101#36#9 : Suiv
	**/

	var menus = []entity.Menu{
		{
			ID:        1,
			Category:  "follow-competition",
			Name:      "Live match",
			Slug:      "lm",
			KeyPress:  "1",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        2,
			Category:  "follow-competition",
			Name:      "Live match",
			Slug:      "lm-live-match",
			KeyPress:  "1",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        3,
			Category:  "follow-competition",
			Name:      "Schedule",
			Slug:      "lm-schedule",
			KeyPress:  "2",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        4,
			Category:  "follow-competition",
			Name:      "Line Up",
			Slug:      "lm-line-up",
			KeyPress:  "3",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        5,
			Category:  "follow-competition",
			Name:      "match Stats",
			Slug:      "lm-match-stats",
			KeyPress:  "4",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        6,
			Category:  "follow-competition",
			Name:      "Display Live match",
			Slug:      "lm-display-livematch",
			KeyPress:  "5",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        7,
			Category:  "follow-competition",
			Name:      "Flash News",
			Slug:      "flash-news",
			KeyPress:  "2",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        8,
			Category:  "creditgoal",
			Name:      "Crédit Goal",
			Slug:      "credit-goal",
			KeyPress:  "3",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        9,
			Category:  "follow-team",
			Name:      "Champ. Mali",
			Slug:      "champ",
			KeyPress:  "4",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        10,
			Category:  "follow-team",
			Name:      "Results",
			Slug:      "champ-results",
			KeyPress:  "1",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        11,
			Category:  "follow-team",
			Name:      "Standings",
			Slug:      "champ-standings",
			KeyPress:  "2",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        12,
			Category:  "follow-team",
			Name:      "Schedule",
			Slug:      "champ-schedule",
			KeyPress:  "3",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        13,
			Category:  "follow-team",
			Name:      "Team",
			Slug:      "champ-team",
			KeyPress:  "4",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        14,
			Category:  "follow-team",
			Name:      "Crédit Score",
			Slug:      "champ-credit-score",
			KeyPress:  "5",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        15,
			Category:  "follow-team",
			Name:      "Crédit Goal",
			Slug:      "champ-creditgoal",
			KeyPress:  "6",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        16,
			Category:  "follow-team",
			Name:      "SMS Alerte",
			Slug:      "champ-sms-alerte",
			KeyPress:  "7",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        17,
			Category:  "follow-team",
			Name:      "SMS Alerte Equipe",
			Slug:      "champ-sms-alerte-equipe",
			KeyPress:  "8",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        18,
			Category:  "prediction",
			Name:      "Prédiction",
			Slug:      "prediction",
			KeyPress:  "5",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        19,
			Category:  "follow-competition",
			Name:      "SMS Alerte",
			Slug:      "sms-alerte",
			KeyPress:  "6",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        20,
			Category:  "follow-competition",
			Name:      "Kit Foot",
			Slug:      "sms-kit-foot",
			KeyPress:  "1",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        21,
			Category:  "follow-competition",
			Name:      "Europe",
			Slug:      "sms-foot-europe",
			KeyPress:  "2",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        22,
			Category:  "follow-competition",
			Name:      "Afrique",
			Slug:      "sms-foot-afrique",
			KeyPress:  "3",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        23,
			Category:  "follow-competition",
			Name:      "SMS Alerte Equipe",
			Slug:      "sms-alerte-equipe",
			KeyPress:  "4",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        24,
			Category:  "follow-competition",
			Name:      "Foot International",
			Slug:      "sms-foot-international",
			KeyPress:  "5",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        25,
			Category:  "follow-competition",
			Name:      "Kit Foot",
			Slug:      "kit-foot",
			KeyPress:  "7",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        26,
			Category:  "follow-competition",
			Name:      "Alerte Champ. Mali + Equipe",
			KeyPress:  "1",
			Slug:      "kit-foot-champ",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        27,
			Category:  "follow-competition",
			Name:      "Alerte Premier League + Equipe",
			Slug:      "kit-foot-premier-league",
			KeyPress:  "2",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        28,
			Category:  "follow-competition",
			Name:      "Alerte La Liga + Equipe",
			Slug:      "kit-foot-la-liga",
			KeyPress:  "3",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        29,
			Category:  "follow-competition",
			Name:      "Alerte Ligue 1 + Equipe",
			Slug:      "kit-foot-ligue-1",
			KeyPress:  "4",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        30,
			Category:  "follow-competition",
			Name:      "Alerte Serie A + Equipe",
			Slug:      "kit-foot-serie-a",
			KeyPress:  "5",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        31,
			Category:  "follow-competition",
			Name:      "Alerte Bundesligue + Equipe",
			KeyPress:  "6",
			Slug:      "kit-foot-bundesligue",
			IsConfirm: true,
			IsActive:  true,
		},
		{
			ID:        32,
			Category:  "follow-competition",
			Name:      "Foot Europe",
			KeyPress:  "7",
			Slug:      "foot-europe",
			IsConfirm: false,
			IsActive:  true,
		},
		{
			ID:        33,
			Category:  "follow-competition",
			Name:      "Champion League",
			Slug:      "foot-europe-champion-league",
			KeyPress:  "1",
			IsConfirm: false,
			IsActive:  true,
		},
		{
			ID:        34,
			Category:  "follow-competition",
			Name:      "Premier League",
			KeyPress:  "2",
			Slug:      "foot-europe-premier-league",
			IsConfirm: false,
			IsActive:  true,
		},
		{
			ID:        35,
			Category:  "follow-competition",
			Name:      "La Liga",
			Slug:      "foot-europe-la-liga",
			KeyPress:  "3",
			IsConfirm: false,
			IsActive:  true,
		},
		{
			ID:        36,
			Category:  "follow-competition",
			Name:      "Ligue 1",
			Slug:      "foot-europe-ligue-1",
			KeyPress:  "4",
			IsConfirm: false,
			IsActive:  true,
		},
		{
			ID:        37,
			Category:  "follow-competition",
			Name:      "L. Europa",
			Slug:      "foot-europe-l-europa",
			KeyPress:  "5",
			IsConfirm: false,
			IsActive:  true,
		},
		{
			ID:        38,
			Category:  "follow-competition",
			Name:      "Serie A",
			Slug:      "foot-europe-serie-a",
			KeyPress:  "6",
			IsConfirm: false,
			IsActive:  true,
		},
		{
			ID:        39,
			Category:  "follow-competition",
			Name:      "Bundesligua",
			Slug:      "foot-europe-bundesligua",
			KeyPress:  "7",
			IsConfirm: false,
			IsActive:  true,
		},
		{
			ID:        40,
			Category:  "follow-competition",
			Name:      "Champ Portugal",
			Slug:      "foot-europe-champ-portugal",
			KeyPress:  "8",
			IsConfirm: false,
			IsActive:  true,
		},
	}

	if db.Find(&country).RowsAffected == 0 {
		for i, _ := range countries {
			db.Model(&entity.Country{}).Create(&countries[i])
		}
		log.Println("countries migrated")
	}

	if db.Find(&service).RowsAffected == 0 {
		for i, _ := range services {
			db.Model(&entity.Service{}).Create(&services[i])
		}
		log.Println("services migrated")
	}

	if db.Find(&content).RowsAffected == 0 {
		for i, _ := range contents {
			db.Model(&entity.Content{}).Create(&contents[i])
		}
		log.Println("contents migrated")
	}

	if db.Find(&schedule).RowsAffected == 0 {
		for i, _ := range schedules {
			db.Model(&entity.Schedule{}).Create(&schedules[i])
		}
		log.Println("schedules migrated")
	}

	if db.Find(&menu).RowsAffected == 0 {
		for i, _ := range menus {
			db.Model(&entity.Menu{}).Create(&menus[i])
		}
		log.Println("menus migrated")
	}
}
