package cmd

import (
	"log"
	"time"

	"github.com/idprm/go-football-alert/internal/domain/entity"
	"gorm.io/gorm"
)

func seederDB(db *gorm.DB) {
	var service []entity.Service
	var content []entity.Content
	var schedule []entity.Schedule
	var menu []entity.Menu

	// 1 : Live match ( Display USSD only )
	// 2 : Flash News ( Display USSD Only )
	// 3 : SMS Alerte ( Follow League and/or Team ) info sent via SMS
	// 4 : Credit Goal ( Not to live at lunch )
	// 5 : Predict and Win ( Not to live at lunch )
	// 6 : Pronostic : Data to be uploaded into CMS to be shared via SMS , there is two segment of sub in this service

	// Live Match :
	// Day : 25
	// Week : 100
	// Month : 250
	// —————
	// Flash News :
	// Day : 25
	// Week : 100
	// Month : 250
	// —————-
	// SMS Alerte :
	// Day : 50
	// Week : 200
	// Month : 500
	// ———-
	// Prediction/Pronostic safe :
	// Day : 50
	// Week : 200
	// Month : 500
	// ————
	// Prediction/Pronostic safe & Combined :
	// Day : 100
	// Week : 500
	// Month : 1500

	var services = []entity.Service{
		{
			ID:         1,
			Category:   "LIVEMATCH",
			Channel:    ACT_USSD,
			Name:       "LiveMatch1",
			Code:       "LM1",
			Package:    "jour",
			Price:      25,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 1,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         2,
			Category:   "LIVEMATCH",
			Channel:    ACT_USSD,
			Name:       "LiveMatch7",
			Code:       "LM7",
			Package:    "semaine",
			Price:      100,
			RewardGoal: 0,
			RenewalDay: 7,
			Currency:   "CFA",
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         3,
			Category:   "LIVEMATCH",
			Channel:    ACT_USSD,
			Name:       "LiveMatch30",
			Code:       "LM30",
			Package:    "mois",
			Price:      250,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 30,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         4,
			Category:   "FLASHNEWS",
			Channel:    ACT_USSD,
			Name:       "FlashNews1",
			Code:       "FN1",
			Package:    "jour",
			Price:      25,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 1,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         5,
			Category:   "FLASHNEWS",
			Channel:    ACT_USSD,
			Name:       "FlashNews1",
			Code:       "FN7",
			Package:    "semaine",
			Price:      100,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 7,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         6,
			Category:   "FLASHNEWS",
			Channel:    ACT_USSD,
			Name:       "FlashNews30",
			Code:       "FN30",
			Package:    "mois",
			Price:      250,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 30,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         7,
			Category:   "SMSALERTE_COMPETITION",
			Channel:    "SMS",
			Name:       "SMSAlerteCompetition1",
			Code:       "SAC1",
			Package:    "jour",
			Price:      50,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 1,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         8,
			Category:   "SMSALERTE_COMPETITION",
			Channel:    "SMS",
			Name:       "SMSAlerteCompetition7",
			Code:       "SAC7",
			Package:    "semaine",
			Price:      200,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 7,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         9,
			Category:   "SMSALERTE_COMPETITION",
			Channel:    "SMS",
			Name:       "SMSAlerteCompetition30",
			Code:       "SAC30",
			Package:    "mois",
			Price:      500,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 30,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},

		{
			ID:         10,
			Category:   "SMSALERTE_EQUIPE",
			Channel:    "SMS",
			Name:       "SMSAlerteEquipe1",
			Code:       "SAE1",
			Package:    "jour",
			Price:      50,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 1,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         11,
			Category:   "SMSALERTE_EQUIPE",
			Channel:    "SMS",
			Name:       "SMSAlerteEquipe7",
			Code:       "SAC7",
			Package:    "semaine",
			Price:      200,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 7,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         9,
			Category:   "SMSALERTE_COMPETITION",
			Channel:    "SMS",
			Name:       "SMSAlerteCompetition30",
			Code:       "SAC30",
			Package:    "mois",
			Price:      500,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 30,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},

		{
			ID:         10,
			Category:   "PRONOSTIC_SAFE",
			Channel:    "SMS",
			Name:       "PronosticSafe1",
			Code:       "PS1",
			Package:    "jour",
			Price:      50,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 1,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         11,
			Category:   "PRONOSTIC_SAFE",
			Channel:    "SMS",
			Name:       "PronosticSafe7",
			Code:       "PS7",
			Package:    "semaine",
			Price:      200,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 7,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         12,
			Category:   "PRONOSTIC_SAFE",
			Channel:    "SMS",
			Name:       "PronosticSafe30",
			Code:       "PS30",
			Package:    "mois",
			Price:      500,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 30,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         13,
			Category:   "PRONOSTIC_COMBINED",
			Channel:    "SMS",
			Name:       "PronosticCombined1",
			Code:       "PC1",
			Package:    "jour",
			Price:      50,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 1,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         14,
			Category:   "PRONOSTIC_COMBINED",
			Channel:    "SMS",
			Name:       "PronosticCombined7",
			Code:       "PC7",
			Package:    "semaine",
			Price:      200,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 7,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         15,
			Category:   "PRONOSTIC_COMBINED",
			Channel:    "SMS",
			Name:       "PronosticCombined30",
			Code:       "PS30",
			Package:    "mois",
			Price:      500,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 30,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         16,
			Category:   "PRONOSTIC_VIP",
			Channel:    "SMS",
			Name:       "PronosticVIP1",
			Code:       "PV1",
			Package:    "jour",
			Price:      50,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 1,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         17,
			Category:   "PRONOSTIC_VIP",
			Channel:    "SMS",
			Name:       "PronosticVIP7",
			Code:       "PV7",
			Package:    "semaine",
			Price:      200,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 7,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
		{
			ID:         18,
			Category:   "PRONOSTIC_VIP",
			Channel:    "SMS",
			Name:       "PronosticVIP30",
			Code:       "PV30",
			Package:    "mois",
			Price:      500,
			Currency:   "CFA",
			RewardGoal: 0,
			RenewalDay: 30,
			FreeDay:    1,
			UrlTelco:   "http://172.17.111.40:8080/services/OrangeService.OrangeServiceHttpSoap11Endpoint/",
			UserTelco:  "ESERV",
			PassTelco:  "WS001",
			UrlMT:      "http://10.106.0.3:4445/cgi-bin/sendsms?smsc=MOBIMIUM&username={username}&password={password}&from={from}&to={to}&text={text}",
			UserMT:     "send",
			PassMT:     "sendsms",
			ScSubMT:    "37405",
			ScUnsubMT:  "37484",
			ShortCode:  "????",
			UssdCode:   "#101#36#",
			IsActive:   true,
		},
	}

	var contents = []entity.Content{
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_LIVE_MATCH_SUB,
			Value:    "Match en Direct: Cher client  Vous avez souscrit avec succes! Vous recevrez toutes les infos en direct. {price}{currency}/{duration}",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FLASH_NEWS_SUB,
			Value:    "Actu Flash: Vous avez souscrit avec succes! Vous recevrez toutes les infos en direct. {price}{currency}/{duration}",
		},

		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_TEAM_SUB,
			Value:    "SMS Alerte: Vous avez souscrit avec succes pour suivre votre equipe favorite {team}! Vous recevrez toutes les infos en direct. {price}{currency}/souscription",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_TEAM_ALREADY_SUB,
			Value:    "SMS Alerte: Vous avez deja souscrit a cette equipe.",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_TEAM_UNVALID_SUB,
			Value:    "SMS Alerte: Desole, votre choix n est pas valide. Envoyez de nouveau au {sc} le nom de votre equipe pour obtenir toutes les infos.",
		},
		{
			Category: ACT_NOTIFICATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_TEAM_EXPIRE_SUB,
			Value:    "SMS Alerte: Desole mais votre abonnement pour suivre votre equipe vient de se terminer. Pour le renouveler, envoyer au {sc} le nom de lequipe a suivre. {price}{currency}",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_COMPETITION_SUB,
			Value:    "SMS Alerte: Vous avez souscrit avec succes pour suivre {league}! Vous recevrez toutes les infos en direct. {price}{currency}/souscription",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_COMPETITION_ALREADY_SUB,
			Value:    "SMS Alerte: Vous avez deja souscrit a cette competition.",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_COMPETITION_UNVALID_SUB,
			Value:    "SMS Alerte: Desole, mais votre choix n est pas valide. Renvoyez au {sc} la competition que vous voulez suivre en direct.",
		},
		{
			Category: ACT_NOTIFICATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_COMPETITION_EXPIRE_SUB,
			Value:    "SMS Alerte: Desole mais votre abonnement pour suivre votre competition vient de se terminer. Pour le renouveler, envoyer au {sc} le nom de la competition a suivre.",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_FOLLOW_UNVALID_SUB,
			Value:    "SMS Alerte: Désolé, votre sélection n'est pas valide. Soumettez votre compétition ou le nom de votre équipe à {sc} pour obtenir toutes les informations. {price}{currency}/souscription",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PRONOSTIC_SAFE_SUB,
			Value:    "Pronostic: Vous avez souscrit avec succes! Vous recevrez toutes les pronostics en direct. {price}{currency}/{duration}",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PRONOSTIC_COMBINED_SUB,
			Value:    "Pronostic: Vous avez souscrit avec succes! Vous recevrez toutes les pronostics ticket en direct. {price}{currency}/{duration}",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PRONOSTIC_VIP_SUB,
			Value:    "Pronostic: Vous avez souscrit avec succes! Vous recevrez toutes les pronostics VIP en direct. {price}{currency}/{duration}",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_INFO,
			Value:    "Info Services FFC: [#101#36#] USSD /SMS Alerte Equipe /SMS Alerte Competition",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_STOP,
			Value:    "OFC : Votre abonnement au service a ete resilié. Vous ne serez plus facturé et vous ne pourrez plus accéder à ce service à la fin de l'échéance de votre abonnement.",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_OTP,
			Value:    "Votre code OTP est {pin}. Services OFC",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_CREDIT_GOAL_SUB,
			Value:    "Credit Goal: Votre participation a ete enregistree. Si {team} marque des buts lors du prochain match, vous recevrez {reward_per_goal}{currency} de credit par but. {price}{curency}/souscription",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_CREDIT_GOAL_ALREADY_SUB,
			Value:    "Credit Goal: Desole, vous avez deja une equipe favorite pour le prochain match de {league}. Vous pourrez choisir une autre equipe pour la journee suivante au {sc}.",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_CREDIT_GOAL_UNVALID_SUB,
			Value:    "Credit Goal: Desole, votre choix n est pas valide. Renvoyez par SMS au {sc} votre equipe favorite pour le prochain match. {price}{currency}/souscription",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_CREDIT_GOAL_MATCH_END_PAYOUT,
			Value:    "Credit Goal: Felicitations! Le score final du match {home} - {away} est {score}. Votre compte va etre credite de {price}{currency} [CFA]",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_CREDIT_GOAL_MATCH_INCENTIVE,
			Value:    "Credit Goal: la prochaine journee de {league} va commencer. Soutenez votre equipe et gagnez du credit. Envoyez au {sc} votre equipe. {price}{currency}/souscription",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_SUB,
			Value:    "Prono: Faites vos pronostics pour {home} - {away}. Envoyez au {sc}: {league}[12] plus [1] pour {home}, [2] pour {away} ou [3] pour un nul. {price}{currency}/SMS",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_SUB_BET_WIN,
			Value:    "Prono: Votre pronostic a ete enregistre avec une victoire de: {winner}. Votre compte a ete debite de {price}{currency} [CFA]. Bonne Chance!",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_SUB_BET_DRAW,
			Value:    "Prono: Votre pronostic est un match nul pour le match {home} - {away}. Votre compte a ete debite de {price}{currency} [CFA]. Bonne Chance!",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_UNVALID_SUB,
			Value:    "Prono: Desole, votre choix n est pas valide. Renvoyez votre choix au {sc} ou le nom de votre competition. {price}{currency}/SMS",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_SUB_REJECT_MATCH_END,
			Value:    "Prono: Desole, cette competition est terminee. Envoyez le nom de votre competition au {sc} pour recevoir les invitations a pronostiquer. {price}{currency}/SMS",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_SUB_REJECT_MATCH_STARTED,
			Value:    "Prono: Desole, vous ne pouvez plus faire de pronostics sur ce match. SMS Confirmation Retentez votre chance Free of charge SMS Text Template: G21(NEW) pour le prochain match {price}{currency}/SMS",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_MATCH_END_WINNER_AIRTIME,
			Value:    "Prono: Bravo! Bon pronostic pour le match {home} - {away}, vous avez gagne {reward}{currency} de credit de com par tirage au sort. Votre compte sera credite sous 48h.",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_MATCH_END_WINNER_LOTERY,
			Value:    "Bravo! Vous avez fait un bon pronostic pour le match {home} - {away}, vous venez de gagner un lot, aller à la boutique Orange pour les obtenir.",
		},
		{
			Category: ACT_CONFIRMATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_MATCH_END_LUCKY_LOSER,
			Value:    "Prono: Vous avez fait un bon pronostic, mais vous n avez pas ete tire au sort pour gagner {reward}{currency}. Retentez votre chance pour le prochain match au {sc}. {price}{currency}/SMS",
		},
		{
			Category: ACT_NOTIFICATION,
			Channel:  ACT_SMS,
			Name:     SMS_PREDICT_MATCH_END_LOSER_NOTIF,
			Value:    "Prono: Desole! Votre pronostic n a pas ete le bon pour le match {home}-{away}. Retentez votre chance pour les prochains matchs .Bonne chance!",
		},
	}

	var schedules = []entity.Schedule{
		{
			Name:       ACT_SMS_ALERTE,
			PublishAt:  time.Now(),
			UnlockedAt: time.Now(),
			IsUnlocked: false,
		},
		{
			Name:       ACT_SMS_ALERTE,
			PublishAt:  time.Now(),
			UnlockedAt: time.Now(),
			IsUnlocked: false,
		},
		{
			Name:       ACT_SMS_ALERTE,
			PublishAt:  time.Now(),
			UnlockedAt: time.Now(),
			IsUnlocked: false,
		},
		{
			Name:       ACT_SMS_ALERTE,
			PublishAt:  time.Now(),
			UnlockedAt: time.Now(),
			IsUnlocked: false,
		},
		{
			Name:       ACT_CREDIT_GOAL,
			PublishAt:  time.Now(),
			UnlockedAt: time.Now(),
			IsUnlocked: false,
		},
		{
			Name:       ACT_PREDICT_WIN,
			PublishAt:  time.Now(),
			UnlockedAt: time.Now(),
			IsUnlocked: false,
		},
	}

	if db.Find(&service).RowsAffected == 0 {
		for i, _ := range services {
			db.Model(&entity.Service{}).Create(&services[i])
		}
		log.Println("services migrated")
	}

	if db.Find(&content).RowsAffected == 0 {
		for i, _ := range contents {
			db.Model(&entity.Content{}).Create(&contents[i])
		}
		log.Println("contents migrated")
	}

	if db.Find(&schedule).RowsAffected == 0 {
		for i, _ := range schedules {
			db.Model(&entity.Schedule{}).Create(&schedules[i])
		}
		log.Println("schedules migrated")
	}

	if db.Find(&menu).RowsAffected == 0 {
		for i, _ := range menus {
			db.Model(&entity.Menu{}).Create(&menus[i])
		}
		log.Println("menus migrated")
	}
}
