name: CI

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile.listener
            image: idprm/fb-alert-listener-service
          - dockerfile: ./Dockerfile.ussd
            image: idprm/fb-alert-ussd-service
          - dockerfile: ./Dockerfile.sms
            image: idprm/fb-alert-sms-service
          - dockerfile: ./Dockerfile.news
            image: idprm/fb-alert-news-service
          - dockerfile: ./Dockerfile.sms_alerte
            image: idprm/fb-alert-sms-alerte-service
          - dockerfile: ./Dockerfile.pronostic
            image: idprm/fb-alert-pronostic-service
          - dockerfile: ./Dockerfile.credit_goal
            image: idprm/fb-alert-credit-goal-service
          - dockerfile: ./Dockerfile.predict_win
            image: idprm/fb-alert-predict-win-service
          - dockerfile: ./Dockerfile.renewal
            image: idprm/fb-alert-renewal-service
          - dockerfile: ./Dockerfile.retry
            image: idprm/fb-alert-retry-service
          - dockerfile: ./Dockerfile.mt
            image: idprm/fb-alert-mt-service
          - dockerfile: ./Dockerfile.pub_scraping_fixtures
            image: idprm/fb-alert-pub-scraping-fixtures-service
          - dockerfile: ./Dockerfile.pub_scraping_prediction
            image: idprm/fb-alert-pub-scraping-prediction-service
          - dockerfile: ./Dockerfile.pub_scraping_news
            image: idprm/fb-alert-pub-scraping-news-service
          - dockerfile: ./Dockerfile.pub_sms_alerte
            image: idprm/fb-alert-pub-sms-alerte-service
          - dockerfile: ./Dockerfile.pub_pronostic
            image: idprm/fb-alert-pub-pronostic-service
          - dockerfile: ./Dockerfile.pub_credit_goal
            image: idprm/fb-alert-pub-credit-goal-service
          - dockerfile: ./Dockerfile.pub_predict_win
            image: idprm/fb-alert-pub-predict-win-service
          - dockerfile: ./Dockerfile.pub_renewal
            image: idprm/fb-alert-pub-renewal-service
          - dockerfile: ./Dockerfile.pub_retry
            image: idprm/fb-alert-pub-retry-service

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
