name: CI

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile.listener
            image: idprm/fb-alert-listener-service
          - dockerfile: ./Dockerfile.ussd
            image: idprm/fb-alert-ussd-service
          - dockerfile: ./Dockerfile.sms
            image: idprm/fb-alert-sms-service
          - dockerfile: ./Dockerfile.mo
            image: idprm/fb-alert-mo-service
          - dockerfile: ./Dockerfile.mt
            image: idprm/fb-alert-mt-service
          - dockerfile: ./Dockerfile.renewal
            image: idprm/fb-alert-renewal-service
          - dockerfile: ./Dockerfile.retry
            image: idprm/fb-alert-retry-service
          - dockerfile: ./Dockerfile.prediction
            image: idprm/fb-alert-prediction-service
          - dockerfile: ./Dockerfile.credit_goal
            image: idprm/fb-alert-credit-goal-service
          - dockerfile: ./Dockerfile.follow_team
            image: idprm/fb-alert-follow-team-service
          - dockerfile: ./Dockerfile.follow_competition
            image: idprm/fb-alert-follow-competition-service
          - dockerfile: ./Dockerfile.pub_scraping
            image: idprm/fb-alert-pub-scraping-service
          - dockerfile: ./Dockerfile.pub_renewal
            image: idprm/fb-alert-pub-renewal-service
          - dockerfile: ./Dockerfile.pub_retry
            image: idprm/fb-alert-pub-retry-service
          - dockerfile: ./Dockerfile.pub_prediction
            image: idprm/fb-alert-pub-prediction-service
          - dockerfile: ./Dockerfile.pub_credit_goal
            image: idprm/fb-alert-pub-credit-goal-service
          - dockerfile: ./Dockerfile.pub_follow_team
            image: idprm/fb-alert-pub-follow-team-service
          - dockerfile: ./Dockerfile.pub_follow_competition
            image: idprm/fb-alert-pub-follow-competition-service

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
